config/routes.rb
require "sidekiq/web"
require "admin_constraint"
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  get "auth/:provider/callback", to: "sessions_google#create"
  get "auth/failure", to: redirect("/")
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  post "/login", to: "sessions#create"
  namespace :admin do
    get "/", to: "base#index"
    post "/", to: "base#index"
    resources :addresses
    resources :brands, except: :show
    resources :products, except: :show do
      post :active, on: :member
    end
    resources :orders
    resources :payments, except: :show
    resources :rates, only: %i(index update destroy)
    resources :shippings
    resources :slides, except: :show
    resources :users do
      post :activated, on: :member
    end
    resources :categories, except: :show do
      post :active, on: :member
    end
    mount Sidekiq::Web, at: "/sidekiq", :constraints => AdminConstraint.new
  end

  root "products#index"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to:"users#new"
  get "/my-account", to: "users#show"
  get "/shopping_cart", to: "cart#shopping_cart"
  get "/signup", to:"users#new"
  get "/users/:id/edit", to: "users#edit", as: :update_account
  get "search(/:search)", to: "search#index", as: :search
  get "search_brand(/:search)", to: "search1#index", as: :search_brand
  root "products#index"
  resources :products, only: :show do
    resources :rates, only: :create
    resources :wishlists, only: :create
    get "/new", to: "products#new_products", on: :collection
    get :hot, on: :collection
    resources :comments, only: :create
  end
  resources :wishlists, only: %i(index destroy)
  resources :account_activations, only: :edit
  patch "/update-account/:id", to: "users#update", as: :edit_account
  post "/add_to_cart/:id", to: "carts#add", as: :add_to_cart
  post "/remove_cart/:id", to: "carts#destroy", as: :remove_cart
  post "/remove_product_from_cart/:id", to: "carts#destroy",
    as: :remove_product_from_cart
  post "/signup", to:"users#create"
  post "/update_cart/:id", to: "carts#update", as: :update_cart

  resources :products
  resources :account_activations, only: :edit
  resources :carts, only: :index
  resources :addresses
  resources :checkouts, only: %i(index create) do
    collection do
      get "/ajax_address", to: "checkouts#ajax_address"
    end
  end
  resources :categories, only: %i(index show)
  resources :brands, only: %i(index show)
  get "*path", to: redirect("/")
  resources :orders_history, only: %i(index show)
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :load_address, only: %i(update destroy edit)

  def index
    @addresses = current_user.addresses
  end

  def new
    @address = Address.new
  end

  def create
    @address = current_user.addresses.build address_params

    if @address.save
      flash[:success] = t "addresses.save_success"
      redirect_forwarding_url addresses_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @address.update_attributes address_params
      flash[:success] = t "addresses.save_success"
      redirect_to addresses_path
    else
      render :new
    end
  end

  def destroy
    if @address.destroy
      flash[:success] = t "addresses.delete_success"
    else
      flash[:warning] = t "addresses.delete_error"
    end
    redirect_to addresses_path
  end

  private

  def address_params
    params.require(:address).permit Address::FRONT_ADDRESS_PARAMS
  end

  def load_address
    @address = Address.find_by id: params[:id]
    return if @address
    flash[:danger] = t "addresses.address_not_found"
    redirect_to addresses_path
  end
end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < Admin::BaseController
  before_action :find_address, only: %i(update destroy edit)

  def index
    @addresses = Address.page(params[:page]).per Settings.limit_page
  end

  def edit; end

  def update
    if @address.update address_params
      flash[:success] = t ".save_success"
      redirect_to admin_addresses_path
    else
      render :new
    end
  end

  def create
    @address = Address.new address_params

    if @address.save
      flash[:success] = t ".save_success"
      redirect_to admin_addresses_path
    else
      render :new
    end
  end

  def new
    @address = Address.new
  end

  def destroy
    if @address.destroy
      flash[:success] = t(".delete_success")
    else
      flash[:warning] = t(".delete_error")
    end
    redirect_to admin_addresses_path
  end

  private

  def address_params
    params.require(:address).permit Address::ADDRESS_PARAMS
  end

  def find_address
    @address = Address.find_by id: params[:id]
    return if @address
    flash[:danger] = t ".address_not_found"
    redirect_to admin_addresses_path
  end
end

app/views/admin/addresses/_form.html.erb
<%= form_for [:admin, @address] do |f| %>
  <%= render "layouts/error_messages", object: f.object %>
  <% if @address.new_record? %>
  <div class="form-group">
    <%= f.label :alias, t(".alias") %>
    <%= f.text_field :alias, class: "form-control" %>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :full_name, t(".full_name") %>
    <%= f.text_field :full_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :post_code, t(".post_code") %>
    <%= f.text_field :post_code, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city, t(".city") %>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :country, t(".country") %>
    <%= f.text_field :country, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone, t(".phone") %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :user_id, t(".choose_user") %>
    <%= f.select(:user_id, options_from_collection_for_select(User.all,
      :id, :full_name), {}, {class: "form-control"}) %>
  </div>
  <%= f.button t(".btn_save"), type: :submit, class: "btn btn-default" %>
  <%= f.button t(".btn_reset"), type: :reset, class: "btn btn-default" %>
<% end %>

app/views/admin/addresses/edit.html.erb
<% provide :title, t(".title") %>
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t ".title" %>
          <small><%= t ".add" %></small>
        </h1>
      </div>
      <div class="col-lg-7" style="padding-bottom:120px">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/addresses/index.html.erb
<% provide :title, t(".title") %>
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t ".title" %>
          <small><%= t ".list" %></small>
        </h1>
      </div>
      <table class="table table-striped table-bordered table-hover"
         id="dataTables-example">
        <thead>
          <tr align="center">
            <th><%= t ".id" %></th>
            <th><%= t ".alias" %></th>
            <th><%= t ".full_name" %></th>
            <th><%= t ".delete" %></th>
          </tr>
        </thead>
        <tbody>
          <% @addresses.each do |address| %>
          <tr class="odd gradeX" align="center">
            <td><%= address.id %></td>
            <td><%= address.alias %></td>
            <td><%= address.full_name %></td>
            <td class="center">
              <i class="fa fa-trash-o  fa-fw"></i>
              <%= link_to t(".delete"), admin_address_path(address),
                method: :delete, data: {confirm: t(".you_sure")} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @addresses %>
    </div>
  </div>
</div>

app/views/admin/addresses/new.html.erb
<% provide :title, t(".title") %>
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t ".title" %>
          <small><%= t ".add" %></small>
        </h1>
      </div>
      <div class="col-lg-7" style="padding-bottom:120px">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>