config/routes.rb
require "sidekiq/web"
require "admin_constraint"
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  get "auth/:provider/callback", to: "sessions_google#create"
  get "auth/failure", to: redirect("/")
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  post "/login", to: "sessions#create"
  namespace :admin do
    get "/", to: "base#index"
    post "/", to: "base#index"
    resources :addresses
    resources :brands, except: :show
    resources :products, except: :show do
      post :active, on: :member
    end
    resources :orders
    resources :payments, except: :show
    resources :rates, only: %i(index update destroy)
    resources :shippings
    resources :slides, except: :show
    resources :users do
      post :activated, on: :member
    end
    resources :categories, except: :show do
      post :active, on: :member
    end
    mount Sidekiq::Web, at: "/sidekiq", :constraints => AdminConstraint.new
  end

  root "products#index"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to:"users#new"
  get "/my-account", to: "users#show"
  get "/shopping_cart", to: "cart#shopping_cart"
  get "/signup", to:"users#new"
  get "/users/:id/edit", to: "users#edit", as: :update_account
  get "search(/:search)", to: "search#index", as: :search
  get "search_brand(/:search)", to: "search1#index", as: :search_brand
  root "products#index"
  resources :products, only: :show do
    resources :rates, only: :create
    resources :wishlists, only: :create
    get "/new", to: "products#new_products", on: :collection
    get :hot, on: :collection
    resources :comments, only: :create
  end
  resources :wishlists, only: %i(index destroy)
  resources :account_activations, only: :edit
  patch "/update-account/:id", to: "users#update", as: :edit_account
  post "/add_to_cart/:id", to: "carts#add", as: :add_to_cart
  post "/remove_cart/:id", to: "carts#destroy", as: :remove_cart
  post "/remove_product_from_cart/:id", to: "carts#destroy",
    as: :remove_product_from_cart
  post "/signup", to:"users#create"
  post "/update_cart/:id", to: "carts#update", as: :update_cart

  resources :products
  resources :account_activations, only: :edit
  resources :carts, only: :index
  resources :addresses
  resources :checkouts, only: %i(index create) do
    collection do
      get "/ajax_address", to: "checkouts#ajax_address"
    end
  end
  resources :categories, only: %i(index show)
  resources :brands, only: %i(index show)
  get "*path", to: redirect("/")
  resources :orders_history, only: %i(index show)
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
  validates :name, presence: true
  scope :order_brand, -> {select(:id, :name).order(name: :asc)}
  scope :search_brand, -> search_name do
    where("brands.name LIKE ?", "%#{search_name}%")
  end
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::BaseController
  before_action :load_brand, only: %i(edit update destroy)

  def index
    @brands = Brand.search_brand(params[:search])
                   .page(params[:page])
                   .per Settings.limit_page
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new brand_params

    if @brand.save
      flash[:success] = t ".create_succeed"
      redirect_to admin_brands_path
    else
      flash[:danger] = t ".create_failed"
      render :new
    end
  end

  def edit; end

  def update
    if @brand.update_attributes brand_params
      flash[:success] = t ".update_succeed"
      redirect_to admin_brands_path
    else
      flash[:danger] = t ".update_failed"
      render :edit
    end
  end

  def destroy
    if @brand.products.empty? && @brand.destroy
      flash[:success] = t ".delete_succeed"
    else
      flash[:danger] = t ".can't_not"
    end
      redirect_to admin_brands_path
  end

  private

  def brand_params
    params.require(:brand).permit :name, :description
  end

  def load_brand
    @brand = Brand.find_by id: params[:id]
    return if @brand
    flash[:danger] = t ".not_found_brand"
    redirect_to admin_brands_path
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :load_brand, only: :show

  def index
    @brands = Brand.order_brand.page(params[:page]).per Settings.record_per_page
  end

  def show
    @products = @brand.products.order_by_name.page(params[:page])
      .per Settings.record_per_page
  end

  private

  def load_brand
    @brand = Brand.find_by id: params[:id]
    return if @brand
    flash[:warning] = t ".not_found"
    redirect_to root_path
  end
end

app/views/admin/brands/_brand.html.erb
<tr class="odd gradeX center">
  <td><%= index_for_list @brands, brand_counter %></td>
  <td><%= brand.name %></td>
  <td><%= brand.products.count %></td>
  <td class="center">
    <i class="fa fa-pencil fa-fw"></i>
    <%= link_to t("admin.edit"), edit_admin_brand_path(brand) %>
  </td>
  <td class="center">
    <i class="fa fa-trash-o fa-fw"></i>
    <%= link_to t("admin.delete"), admin_brand_path(brand),
     method: :delete, data: {confirm: t(".you_sure")}%>
  </td>
</tr>

app/views/admin/brands/_form.html.erb
<%= form_for [:admin, @brand] do |f| %>
  <%= render "layouts/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label :name, t(".name") %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, t(".description") %>
    <%= f.cktext_area :description %>
  </div>
  <%= f.button t("admin.save"), type: :submit, class: "btn btn-default" %>
  <%= f.button t("admin.reset"), type: :reset, class: "btn btn-default" %>
<% end %>

app/views/admin/brands/edit.html.erb
<% provide :title, t(".title") %>
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t ".brand" %>
          <small><%= t ".title" %></small>
        </h1>
      </div>
      <div class="col-lg-7 page-content">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/brands/index.html.erb
<% provide :title, t(".brand") %>
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t ".brand" %>
          <small><%= t ".list" %></small>
        </h1>
      </div>
      <div class="action_btn row col-lg-12">
        <%= form_tag admin_brands_path, method: :get,
          class: "navbar-form navbar-right" do %>
          <%= text_field_tag :search, params[:search], class: "form-control",
            placeholder: t("admin.brands.index.search_an_brand"),
              "data-toggle": "dropdown", require: true %>
          <%= button_tag type: :submit, class: "btn btn-default" do %>
            <i class ="fa fa-search"></i>
          <% end %>
        <% end %>
      </div>
      <div class="action_btn row col-lg-12">
        <%= link_to t(".add_new"), new_admin_brand_url,
          class: "btn btn-default" %>
      </div>
      <table class="table table-striped table-bordered table-hover"
         id="dataTables-example">
        <thead>
          <tr align="center">
            <th><%= t ".stt" %></th>
            <th><%= t ".name" %></th>
            <th><%= t ".product_count" %></th>
            <th><%= t ".edit" %></th>
            <th><%= t ".delete" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "brand", collection: @brands, as: :brand %>
        </tbody>
      </table>
      <%= paginate @brands %>
    </div>
  </div>
</div>

app/views/admin/brands/new.html.erb
<% provide :title, t(".add") %>
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header"><%= t ".brand" %>
          <small><%= t ".add" %></small>
        </h1>
      </div>
      <div class="col-lg-7 page-content">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>