config/routes.rb
require "sidekiq/web"
require "admin_constraint"
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  get "auth/:provider/callback", to: "sessions_google#create"
  get "auth/failure", to: redirect("/")
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  post "/login", to: "sessions#create"
  namespace :admin do
    get "/", to: "base#index"
    post "/", to: "base#index"
    resources :addresses
    resources :brands, except: :show
    resources :products, except: :show do
      post :active, on: :member
    end
    resources :orders
    resources :payments, except: :show
    resources :rates, only: %i(index update destroy)
    resources :shippings
    resources :slides, except: :show
    resources :users do
      post :activated, on: :member
    end
    resources :categories, except: :show do
      post :active, on: :member
    end
    mount Sidekiq::Web, at: "/sidekiq", :constraints => AdminConstraint.new
  end

  root "products#index"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to:"users#new"
  get "/my-account", to: "users#show"
  get "/shopping_cart", to: "cart#shopping_cart"
  get "/signup", to:"users#new"
  get "/users/:id/edit", to: "users#edit", as: :update_account
  get "search(/:search)", to: "search#index", as: :search
  get "search_brand(/:search)", to: "search1#index", as: :search_brand
  root "products#index"
  resources :products, only: :show do
    resources :rates, only: :create
    resources :wishlists, only: :create
    get "/new", to: "products#new_products", on: :collection
    get :hot, on: :collection
    resources :comments, only: :create
  end
  resources :wishlists, only: %i(index destroy)
  resources :account_activations, only: :edit
  patch "/update-account/:id", to: "users#update", as: :edit_account
  post "/add_to_cart/:id", to: "carts#add", as: :add_to_cart
  post "/remove_cart/:id", to: "carts#destroy", as: :remove_cart
  post "/remove_product_from_cart/:id", to: "carts#destroy",
    as: :remove_product_from_cart
  post "/signup", to:"users#create"
  post "/update_cart/:id", to: "carts#update", as: :update_cart

  resources :products
  resources :account_activations, only: :edit
  resources :carts, only: :index
  resources :addresses
  resources :checkouts, only: %i(index create) do
    collection do
      get "/ajax_address", to: "checkouts#ajax_address"
    end
  end
  resources :categories, only: %i(index show)
  resources :brands, only: %i(index show)
  get "*path", to: redirect("/")
  resources :orders_history, only: %i(index show)
end

app/views/layouts/admin/_admin_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "admin", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "admin", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

app/views/layouts/admin/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="navbar-header">
    <a class="navbar-brand" href="/admin"><%= t ".admin_fashion" %></a>
  </div>
  <ul class="nav navbar-top-links navbar-right">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i>
        <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li>
          <i class="fa fa-user fa-fw"></i><%=  current_user.full_name %>
        </li>
        <li>
          <%= link_to edit_admin_user_path(current_user) do  %>
            <i class="fa fa-gear fa-fw"></i><%= t(".setting") %>
          <% end %>
        </li>
        <li class="divider"></li>
        <%= link_to logout_path do %>
          <i class="fa fa-sign-out fa-fw"></i> <%= t(".logout") %>
        <% end %>
      </ul>
    </li>
  </ul>
  <%= render "layouts/admin/sidebar" %>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
      <li class="sidebar-search">
        <div class="input-group custom-search-form">
          <input type="text" class="form-control"
            placeholder="Search...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">
              <i class="fa fa-search"></i>
            </button>
          </span>
        </div>
      </li>
      <li>
        <%= link_to "/admin" do %>
          <i class="fa fa-dashboard fa-fw"></i> <%= t".dashboard" %>
        <% end %>
      </li>
      <li>
        <%= link_to admin_users_path do %>
          <i class="fa fa-bar-chart-o fa-fw"></i> <%= t ".user" %>
          <span class="fa arrow"></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_addresses_path do %>
          <i class="fa fa-bar-chart-o fa-fw"></i> <%= t ".address" %>
          <span class="fa arrow"></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_shippings_path do %>
          <i class="fa fa-bar-chart-o fa-fw"></i> <%= t ".shipping" %>
          <span class="fa arrow"></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_orders_path do %>
          <i class="fa fa-bar-chart-o fa-fw"></i> <%= t ".order" %>
          <span class="fa arrow"></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_brands_path do %>
          <i class="fa fa-bar-chart-o fa-fw"></i> <%= t ".brand" %>
          <span class="fa arrow"></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_categories_path do %>
          <i class="fa fa-bar-chart-o fa-fw"></i> <%= t ".category" %>
          <span class="fa arrow"></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_products_path do %>
          <i class="fa fa-bar-chart-o fa-fw"></i> <%= t ".product" %>
          <span class="fa arrow"></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_slides_path do %>
          <i class="fa fa-bar-chart-o fa-fw"></i> <%= t ".slide" %>
          <span class="fa arrow"></span>
          <% end %>
      </li>
      <li>
        <%= link_to admin_payments_path do %>
          <i class="fa fa-bar-chart-o fa-fw"></i> <%= t ".payment" %>
          <span class="fa arrow"></span>
        <% end %>
      </li>
      <li>
        <%= link_to admin_rates_path do %>
          <i class="fa fa-bar-chart-o fa-fw"></i> <%= t ".rate" %>
          <span class="fa arrow"></span>
        <% end %>
      </li>
    </ul>
  </div>
</div>