config/routes.rb
require "sidekiq/web"
require "admin_constraint"
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  get "auth/:provider/callback", to: "sessions_google#create"
  get "auth/failure", to: redirect("/")
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
  post "/login", to: "sessions#create"
  namespace :admin do
    get "/", to: "base#index"
    post "/", to: "base#index"
    resources :addresses
    resources :brands, except: :show
    resources :products, except: :show do
      post :active, on: :member
    end
    resources :orders
    resources :payments, except: :show
    resources :rates, only: %i(index update destroy)
    resources :shippings
    resources :slides, except: :show
    resources :users do
      post :activated, on: :member
    end
    resources :categories, except: :show do
      post :active, on: :member
    end
    mount Sidekiq::Web, at: "/sidekiq", :constraints => AdminConstraint.new
  end

  root "products#index"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to:"users#new"
  get "/my-account", to: "users#show"
  get "/shopping_cart", to: "cart#shopping_cart"
  get "/signup", to:"users#new"
  get "/users/:id/edit", to: "users#edit", as: :update_account
  get "search(/:search)", to: "search#index", as: :search
  get "search_brand(/:search)", to: "search1#index", as: :search_brand
  root "products#index"
  resources :products, only: :show do
    resources :rates, only: :create
    resources :wishlists, only: :create
    get "/new", to: "products#new_products", on: :collection
    get :hot, on: :collection
    resources :comments, only: :create
  end
  resources :wishlists, only: %i(index destroy)
  resources :account_activations, only: :edit
  patch "/update-account/:id", to: "users#update", as: :edit_account
  post "/add_to_cart/:id", to: "carts#add", as: :add_to_cart
  post "/remove_cart/:id", to: "carts#destroy", as: :remove_cart
  post "/remove_product_from_cart/:id", to: "carts#destroy",
    as: :remove_product_from_cart
  post "/signup", to:"users#create"
  post "/update_cart/:id", to: "carts#update", as: :update_cart

  resources :products
  resources :account_activations, only: :edit
  resources :carts, only: :index
  resources :addresses
  resources :checkouts, only: %i(index create) do
    collection do
      get "/ajax_address", to: "checkouts#ajax_address"
    end
  end
  resources :categories, only: %i(index show)
  resources :brands, only: %i(index show)
  get "*path", to: redirect("/")
  resources :orders_history, only: %i(index show)
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :load_product, except: :index

  def index; end

  def update
    respond_to do |format|
      cart = session[:cart] ||= {}
      @quantity  = params[:quantity].to_i
      cart[@product.id.to_s] = @quantity  if cart[@product.id.to_s]
      session_cart
      format.json
    end
  end

  def add
    respond_to do |format|
      cart = session[:cart] ||= {}
      cart[@product.id.to_s] = cart[@product.id.to_s] ? (cart[@product.id.to_s].to_i + 1) : 1
      session_cart
      format.js
    end
  end

  def destroy
    respond_to do |format|
      cart = session[:cart] ||= {}
      cart.delete(@product.id.to_s) if cart[@product.id.to_s]
      session_cart
      format.js
    end
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
  end
end

app/views/carts/add.js.erb
$(".quantity-item-cart").text("<%= t "header.item", item: @count_product_cart %>");
$(".cart-body .cart-items").html("<%= j(render "layouts/item_cart") %>");
$(".cart-body .cart-total-value").html("<%= currency @total %>");
toastr.options.timeOut = <%= Settings.toastr_timeout %>;
toastr.success("<%= t ".added_cart_success" %>");

app/views/carts/destroy.js.erb
$(".quantity-item-cart").text("<%= t "header.item", item: @count_product_cart %>");
$(".cart-body .cart-items").html("<%= j(render "layouts/item_cart") %>");
$(".cart-body .cart-total-value, .order_total").html("<%= currency @total %>");
$(".beta-shopping-cart-table .cart_item-<%= @product.id %>").remove();
toastr.options.timeOut = <%= Settings.toastr_timeout %>;
toastr.success("<%= t ".removed_cart_success" %>");

app/views/carts/index.html.erb
<div class="inner-header">
  <div class="container">
    <div class="pull-left">
      <h6 class="inner-title"><%= t ".title" %></h6>
    </div>
    <div class="pull-right">
      <div class="beta-breadcrumb font-large">
        <%= link_to t(".home"), root_path %> /
        <span><%= t ".title" %></span>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="container">
  <div id="content">
    <div class="table-responsive">
      <table class="shop_table beta-shopping-cart-table" cellspacing="0">
        <thead>
          <tr>
            <th class="product-name"><%= t ".image" %></th>
            <th class="product-name"><%= t ".product" %></th>
            <th class="product-price"><%= t ".price" %></th>
            <th class="product-quantity"><%= t ".quantity" %></th>
            <th class="product-subtotal"><%= t ".total" %></th>
            <th class="product-remove"><%= t ".remove" %></th>
          </tr>
        </thead>
        <tbody>
          <% @products_cart.each do |product, quantity| %>
          <tr class="cart_item cart_item-<%= product.id %>">
            <td class="product-image">
              <% image = product.images.present? ?
                product.images.first.image.url : "no_image.png" %>
              <%= link_to image_tag(image),
                product_path(product), class: "cart-prduct-image" %>
            </td>
            <td class="product-name">
                <%= product.name %>
            </td>
            <td class="product-price">
              <span class="amount">
                <%= currency product.price %>
              </span>
            </td>
            <td class="product-quantity">
              <%= number_field_tag "", quantity, min: 1, step: 1,
                url_update: update_cart_path(product.id),
                class: "item-quanity" %>
            </td>
            <td class="product-subtotal product-subtotal-<%= product.id %>">
              <span class="amount">
                <%= currency product.price * quantity %>
              </span>
            </td>
            <td class="product-remove">
              <%= link_to remove_product_from_cart_path(product),
                remote: true, method: :post,
                class: "icon-remove-cart" do %>
                <i class="fa fa-trash-o"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="cart-collaterals">
      <div class="cart-totals pull-right">
        <div class="cart-totals-row">
          <h5 class="cart-total-title"><%= t "cart_total" %></h5>
        </div>
        <div class="cart-totals-row">
          <span><%= t "order_total" %></span>
          <span class="order_total">
            <%= currency @total %>
          </span>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

app/views/carts/shopping_cart.html.erb
<div class="container">
  <div id="content">
    <div class="table-responsive">
      <table class="shop_table beta-shopping-cart-table" cellspacing="0">
        <thead>
          <tr>
            <th class="product-name"><%= t "shopping_cart.product" %></th>
            <th class="product-price"><%= t "shopping_cart.price" %></th>
            <th class="product-status"><%= t "shopping_cart.status" %></th>
            <th class="product-quantity"><%= t "shopping_cart.quantity" %></th>
            <th class="product-subtotal"><%= t "shopping_cart.total" %></th>
            <th class="product-remove"><%= t "shopping_cart.remove" %></th>
          </tr>
        </thead>
        <tbody>
          <tr class="cart_item">
            <td class="product-name">
              <div class="media">
                <div class="media-body">
                  <p class="font-large table-title">Men’s Belt</p>
                  <p class="table-option">Color: Red</p>
                  <p class="table-option">Size: M</p>
                  <a class="table-edit" href="#">
                    <%= t "shopping_cart.edit" %></a>
                </div>
                <%= link_to image_tag(Settings.URL_IMAGE+"sp1.jpg", class: "img_product" )%>
              </div>
            </td>
            <td class="product-price">
              <span class="amount">$235.00</span>
            </td>
            <td class="product-status">
              <%= t "shopping_cart.in_stock" %>
            </td>
            <td class="product-quantity">
              <select name="product-quantity" id="product-quantity">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
            </td>
            <td class="product-subtotal">
              <span class="amount">$235.00</span>
            </td>
            <td class="product-remove">
              <a href="#" class="remove"><i class="fa fa-trash-o"></i></a>
            </td>
          </tr>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="cart-collaterals">
      <div class="cart-totals pull-right">
        <div class="cart-totals-row"><h5 class="cart-total-title"><%= t "shipping_cart.cart_totals" %></h5></div>
        <div class="cart-totals-row"><span>
          <%= t "shopping_cart.cart_totals" %>
          </span> <span>$188.00</span></div>
        <div class="cart-totals-row"><span>
          <%= t "shopping_cart.shipping" %>
          </span> <span><%= t "shopping_cart.free_shipping" %></span></div>
        <div class="cart-totals-row"><span>
          <%= t "shopping_cart.order_total" %>
          </span> <span>$188.00</span></div>
      </div>
      <div class="clearfix"></div>
    </div>
    <tfoot>
      <tr>
        <td colspan="6" class="actions">
          <button type="submit" class="beta-btn primary process-button" name="proceed">
            <%= link_to t("shopping_cart.process_checkout"), checkout_path %>
            <i class="fa fa-chevron-right"></i></button>
        </td>
      </tr>
    </tfoot>
    <div class="clearfix"></div>
  </div>
</div>